/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubRouteImport } from './routes/club'
import { Route as EventsRouteImport } from './routes/events'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/events': typeof EventsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/events': typeof EventsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/events': typeof EventsRoute
  '/register': typeof RegisterRoute
  '/schedule': typeof ScheduleRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/events'
    | '/register'
    | '/schedule'
    | '/games/$gameId'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/events'
    | '/register'
    | '/schedule'
    | '/games/$gameId'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/events'
    | '/register'
    | '/schedule'
    | '/games/$gameId'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRoute
  EventsRoute: typeof EventsRoute
  RegisterRoute: typeof RegisterRoute
  ScheduleRoute: typeof ScheduleRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRoute,
  EventsRoute: EventsRoute,
  RegisterRoute: RegisterRoute,
  ScheduleRoute: ScheduleRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
